ALTER TABLE task_type
  ALTER COLUMN schema SET DATA TYPE JSONB;

ALTER TABLE task
  ALTER COLUMN context SET DATA TYPE JSONB,
  ALTER COLUMN context SET DEFAULT 'null'::JSONB,
  ALTER COLUMN result SET DATA TYPE JSONB;
